# Generated by Django 5.1.4 on 2025-11-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('doc_number', models.CharField(blank=True, max_length=100, verbose_name='Номер')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Дата принятия')),
                ('file', models.FileField(blank=True, upload_to='normative/', verbose_name='Файл (PDF)')),
                ('url', models.URLField(blank=True, help_text='Если документ онлайн', verbose_name='Ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
                'ordering': ['-issue_date'],
            },
        ),
    ]
