# Generated by Django 5.1.4 on 2025-11-13 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
            },
        ),
        migrations.CreateModel(
            name='FireObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(verbose_name='Фактический адрес')),
                ('fire_class', models.CharField(choices=[('F1.1', 'Ф1.1 — Детские дошкольные учреждения'), ('F1.2', 'Ф1.2 — Больницы'), ('F1.3', 'Ф1.3 — Жилые дома'), ('F1.4', 'Ф1.4 — Дома для престарелых'), ('F2.1', 'Ф2.1 — Театры, кинотеатры'), ('F2.2', 'Ф2.2 — Музеи, выставки'), ('F3.1', 'Ф3.1 — Торговые центры'), ('F3.2', 'Ф3.2 — Рестораны'), ('F3.3', 'Ф3.3 — Вокзалы'), ('F4.1', 'Ф4.1 — Образовательные учреждения'), ('F4.2', 'Ф4.2 — Научные учреждения'), ('F5.1', 'Ф5.1 — Производственные здания'), ('F5.2', 'Ф5.2 — Склады')], max_length=10, verbose_name='Класс пожарной опасности')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='objects.objecttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Объект надзора',
                'verbose_name_plural': 'Объекты надзора',
            },
        ),
    ]
