# Generated by Django 5.1.4 on 2025-11-13 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsiblePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('phone_work', models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон')),
                ('phone_mobile', models.CharField(blank=True, max_length=20, verbose_name='Мобильный телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначен')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('fire_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='objects.fireobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Ответственное лицо',
                'verbose_name_plural': 'Ответственные лица',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
