# Generated by Django 5.1.4 on 2025-11-13 22:27

import django.db.models.deletion
import inspections.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата проверки')),
                ('notes', models.TextField(blank=True, help_text='Опишите выявленные нарушения', verbose_name='Замечания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершён')], default='draft', max_length=20, verbose_name='Статус')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='inspections/pdfs/', verbose_name='PDF-акт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('fire_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='objects.fireobject', verbose_name='Объект надзора')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Инспектор')),
            ],
            options={
                'verbose_name': 'Акт проверки',
                'verbose_name_plural': 'Акты проверок',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=inspections.models.inspection_photo_upload_path, verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspectionreport')),
            ],
            options={
                'verbose_name': 'Фото нарушения',
                'verbose_name_plural': 'Фото нарушений',
            },
        ),
    ]
