# Generated by Django 5.1.4 on 2025-11-13 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireExtinguisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Уникальный номер по реестру', max_length=100, unique=True, verbose_name='Инвентарный номер')),
                ('type', models.CharField(choices=[('powder', 'Порошковый'), ('co2', 'Углекислотный'), ('foam', 'Пенный'), ('water', 'Водный'), ('halon', 'Хладоновый')], max_length=20, verbose_name='Тип огнетушителя')),
                ('location', models.CharField(help_text='Например: 1-й этаж, коридор у входа', max_length=255, verbose_name='Место установки')),
                ('last_refill_date', models.DateField(help_text='Когда был заправлен или освидетельствован', verbose_name='Дата последней заправки')),
                ('next_check_date', models.DateField(help_text='Когда требуется следующая проверка/заправка', verbose_name='Дата следующей проверки')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, если выведен из эксплуатации', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('fire_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extinguishers', to='objects.fireobject', verbose_name='Объект надзора')),
            ],
            options={
                'verbose_name': 'Огнетушитель',
                'verbose_name_plural': 'Огнетушители',
                'ordering': ['next_check_date'],
            },
        ),
    ]
