# Generated by Django 5.1.4 on 2025-11-13 22:06

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(help_text='Поддерживаемые форматы: PDF, JPG, PNG', upload_to=documents.models.document_upload_path, verbose_name='Файл')),
                ('doc_type', models.CharField(choices=[('evacuation_plan', 'Схема эвакуации'), ('equipment_plan', 'План размещения противопожарного инвентаря'), ('declaration', 'Декларация пожарной безопасности'), ('inspection_report', 'Отчёт о проверке'), ('other', 'Иной документ')], max_length=30, verbose_name='Тип документа')),
                ('valid_until', models.DateField(blank=True, help_text='Оставьте пустым, если бессрочный', null=True, verbose_name='Действителен до')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('version', models.PositiveIntegerField(default=1, help_text='Для отслеживания обновлений', verbose_name='Версия')),
                ('fire_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='objects.fireobject', verbose_name='Объект надзора')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ объекта',
                'verbose_name_plural': 'Документы объектов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
